#!/bin/sh
if [ "$(hostname -s)" != lovelace ]; then
    [ "$#" -eq 0 ] || exit 2
    exec ssh -tt -o BatchMode=yes lovelace fleet-commander
fi
[ "$#" -eq 0 ] || exit 2
exec python -c 'from agent_fleet.commander_client import run; run()'
